### ISSUE TITLE
make问题

### ISSUE THREAD

**Issue by chencong08311** [f1shl3gs/nginx_bundle#1]
你好，make编译的时候提示，“make: *** No rule to make target `https\://github.com/madler/zlib/archive/v1.2.11.zip', needed by `download'.  Stop.” 怎么解决

**Comment by f1shl3gs** [comment]
> 你好，make编译的时候提示，“make: *** No rule to make target `https\://github.com/madler/zlib/archive/v1.2.11.zip', needed by `download'. Stop.” 怎么解决

我没有这个问题，你是如何执行的？

**Comment by f1shl3gs** [comment]
> 你好，make编译的时候提示，“make: *** No rule to make target `https\://github.com/madler/zlib/archive/v1.2.11.zip', needed by `download'. Stop.” 怎么解决

你的操作系统是什么？make版本呢？

**Comment by f1shl3gs** [comment]
@chencong08311 原名为${RESOURCE} 的target在make 3.81上有兼容问题，现在已经修复了，你pull一下最新代码再`make clean && make` 就好了

**Comment by chencong08311** [comment]
make版本 GNU Make 3.81 ，Centos 6.10 Linux VECS012575 2.6.32-754.23.1.el6.x86_64。非常感谢🙏
